#!/bin/sh
# postinst script 
# see: dh_installdeb(1)

set -e

update_os_release()
{
    if [ -e /etc/os-release ]; then
        cp /usr/share/gooroom/adjustments/base-files/os-release /etc/os-release
    fi
}

case "$1" in
    configure|upgrade|update|reconfigure)

    update_os_release
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    triggered)
    update_os_release
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Disabed gooroom-shutdown-trigger.service
#ln -sf /usr/share/debian-system-adjustments/gooroom-shutdown-trigger.service /etc/systemd/system/
#systemctl enable gooroom-shutdown-trigger

exit 0
