#!/bin/sh
# postinst script 
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
update_os_release()
{
    if [ -e /etc/os-release ]; then
        cp /usr/share/gooroom/adjustments/base-files/os-release /etc/os-release
    fi
}

case "$1" in
    configure|upgrade|update|reconfigure)

    update_os_release
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    triggered)
    update_os_release
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Install gooroom-shutdown-trigger.service
ln -sf /usr/share/debian-system-adjustments/gooroom-shutdown-trigger.service /etc/systemd/system/
systemctl enable gooroom-shutdown-trigger

# grub-mkfont
if [ -e /usr/share/fonts/truetype/nanum/NanumBarunpenB.ttf ]; then
  if [ ! -e /boot/grub/fonts ]; then
     mkdir -p /boot/grub/fonts
  fi
  grub-mkfont -s 16 -o /boot/grub/fonts/gooroom-font.pf2 /usr/share/fonts/truetype/nanum/NanumBarunpenB.ttf
fi

#DEBHELPER#

exit 0


