#!/bin/bash

# Bugfix
if [ "$(dpkg-query --showformat='${Version}' --show debian-system-adjustments)" = "1.2.4+grm1u1" ]; then
  [ -e /var/lib/dpkg/info/debian-system-adjustments.postrm ] \
    && rm /var/lib/dpkg/info/debian-system-adjustments.postrm
fi

# Remove Service
if [ -L /etc/systemd/system/gooroom-shutdown-trigger.service ]; then
  # Disable Service
  systemctl is-enabled gooroom-shutdown-trigger
  [ $? = 0 ] && systemctl disable gooroom-shutdown-trigger

  #rm /etc/systemd/system/gooroom-shutdown-trigger.service
fi

# Remove removed-thunar-menu-entries directory
if [ -e /usr/share/debian-system-adjustments/removed-thunar-menu-entries ]; then
  rm -rf /usr/share/debian-system-adjustments/removed-thunar-menu-entries
fi
